### ISSUE TITLE
No AI Spawn eggs partially not listed in creative list for Thermal Series mods

### ISSUE THREAD

**Issue by VallenFrostweaver** [Darkhax-Minecraft/NoAI-Spawn-Eggs#3]
Minecraft 1.16.5
No AI 8.0.3
Thermal Foundation 1.3.2

Looking in the creative No AI tab I can find Blitz eggs but no Blizz or Basalz. These spawn eggs are listed with AI on the JEI menu and on the Thermal Series: Items tab.

**Comment by Darkhax** [comment]
I looked into this issue and it looks like Thermal is registering their spawn eggs with a null entity key. This key is used in Mojang's spawn egg registry so they're basically overwriting their own entries. This seems like it could be pretty dangerous and result in some serious issues with other mods that read from this registry. They seem to have a partial work around in place but this does not work for mods like this which use the vanilla registry data. 

I don't know if it's realistic for them to fix this issue on their end as it would require some pretty big changes to how they do things. I use the registry for performance reasons but I can look into building a new cache by scanning the item registry and then warning when issues like theirs are detected and then try to correct them myself.

**Comment by KingLemming** [comment]
Well the problem is that ALL entity keys are null when Items register. I actually don't know any way around that fact while inheriting from the vanilla spawn egg.

Unfortunately, when I was previously *not* inheriting from the vanilla spawn egg, then I got complaints about that fact, as other mods check for instanceof SpawnEgg. The way the class it set up now, it's entirely fine within that context.

The only place where it breaks is if you're checking the EGGS list specifically - which isn't actually a proper registry, so there's no cross-mod risk. Let me see about some sort of hacky access transformer here and then a direct injection during common setup.

**Comment by KingLemming** [comment]
I've implemented the workaround I talked about in my last post. Simple enough, it just feels dirty, ya know? The eggs also remove themselves from the map on creation (when the entity type resolves as null), so there's no concern about having a null or duplicate entry leftover.

**Comment by Darkhax** [comment]
Thanks for looking into this issue KL, I am glad you were able to work out a fix that works for your setup.

> The only place where it breaks is if you're checking the EGGS list specifically - which isn't actually a proper registry, so there's no cross-mod risk.

The main risks I was talking about is feature incompatibilities. For example something like a safari net item may not be able to find your spawn egg colors. Things like the dispenser were also unable to handle your spawn eggs.
